- config:
    name: 账号密码（极验版）
    base_url: ${ENV(tiger_api_host)}
    verify: False
    variables:
        - existed_pid: unknown
        - wrong_password_source_user: abc
        - wrong_captcha_ticket: aaaaa

# 签发旧登录态
- test:
    name: 登录成功签发旧登录态：请求头Auth-Version不传递-邮箱已注册-密码正确-auth_version不传递
    request:
        method: POST
        url: /tiger/v3/web/accounts/login/security
        headers:
            X-Captcha-Ticket: ${get_captcha_ticket()}
        json:
            identity: ${source_user_email()}
            password: ${source_user_password()}
            pid: $existed_pid
    validate:
        - eq: [status_code, 200]
        - eq: [content.user_info.id, '${source_user_id()}']
        - type_match: [content.auth.token, str]

# 签发新登录态和旧登录态
- test:
    name: 登录成功签发新登录态和旧登录态：请求头Auth-Version不传递-邮箱已注册-密码正确-auth_version=1.0.0
    request:
        method: POST
        url: /tiger/v3/web/accounts/login/security
        headers:
            X-Captcha-Ticket: ${get_captcha_ticket()}
        json:
            identity: ${source_user_email()}
            password: ${source_user_password()}
            pid: $existed_pid
            auth_version: '1.0.0'
    validate:
        - eq: [status_code, 200]
        - eq: [content.user_info.id, '${source_user_id()}']
        - contains: [content.auth, token]
        - contains: [content.auth.token, access]
        - contains: [content.auth.token, refresh]
        - type_match: [content.auth.token, dict]
        - eq: [content.auth.token.access.expires_in, 7200]
        - eq: [content.auth.token.access.type, Bearer]
        - eq: [content.auth.token.refresh.expires_in, 2592000]
        - eq: [content.auth.token.refresh.type, Bearer]

- test:
    name: 登录成功签发新登录态和旧登录态：请求头Auth-Version=1.0.0-邮箱已注册-密码正确-auth_version不传递
    request:
        method: POST
        url: /tiger/v3/web/accounts/login/security
        headers:
            X-Captcha-Ticket: ${get_captcha_ticket()}
            Auth-Version: '1.0.0'
        json:
            identity: ${source_user_email()}
            password: ${source_user_password()}
            pid: $existed_pid
    validate:
        - eq: [status_code, 200]
        - eq: [content.user_info.id, '${source_user_id()}']
        - contains: [content.auth, token]
        - contains: [content.auth.token, access]
        - contains: [content.auth.token, refresh]
        - type_match: [content.auth.token, dict]
        - eq: [content.auth.token.access.expires_in, 7200]
        - eq: [content.auth.token.access.type, Bearer]
        - eq: [content.auth.token.refresh.expires_in, 2592000]
        - eq: [content.auth.token.refresh.type, Bearer]

- test:
    name: 请求头Auth-Version=1.0.0-邮箱已注册-密码正确-auth_version为空字符串
    request:
        method: POST
        url: /tiger/v3/web/accounts/login/security
        headers:
            X-Captcha-Ticket: ${get_captcha_ticket()}
            Auth-Version: '1.0.0'
        json:
            identity: ${source_user_email()}
            password: ${source_user_password()}
            pid: $existed_pid
            auth_version: ''
    validate:
        - eq: [status_code, 400]
        - eq: [content.error_code, A_5]

- test:
    name: 用户名已注册-密码错误
    request:
        method: POST
        url: /tiger/v3/web/accounts/login/security
        headers:
            X-Captcha-Ticket: ${get_captcha_ticket()}
        json:
            identity: ${source_user_username()}
            password: $wrong_password_source_user
            pid: $existed_pid
    validate:
        - eq: [status_code, 403]
        - eq: [content.error_code, AC3_2]

- test:
    name: 用户名已注册-密码不传递
    request:
        method: POST
        url: /tiger/v3/web/accounts/login/security
        headers:
            X-Captcha-Ticket: ${get_captcha_ticket()}
        json:
            identity: ${source_user_username()}
            pid: $existed_pid
    validate:
        - eq: [status_code, 400]
        - eq: [content.error_code, A_5]

- test:
    name: 用户名已注册-ticket不传递
    request:
        method: POST
        url: /tiger/v3/web/accounts/login/security
        json:
            identity: ${source_user_username()}
            password: ${source_user_password()}
            pid: $existed_pid
    validate:
        - eq: [status_code, 403]
        - eq: [content.error_code, GCAP_1]

- test:
    name: 用户名已注册-ticket错误
    request:
        method: POST
        url: /tiger/v3/web/accounts/login/security
        headers:
            X-Captcha-Ticket: $wrong_captcha_ticket
        json:
            identity: ${source_user_username()}
            password: ${source_user_password()}
            pid: $existed_pid
    validate:
        - eq: [status_code, 403]
        - eq: [content.error_code, GCAP_1]