source_user:
  id: 771783
  username: sandy000
  email: sandy000@qq.com
  password: '123456'
  sprite:
    owned: 50  # 象牙螺
    unown: 1   # 编程猫

target_user:
  id: 1855538
  username: sandy001
  password: '123456'
  # 用户无代表精灵