# 需要开启VPN
mysql:
  # 读写权限
  account:
    host: rm-bp173j25673ah67z8879.mysql.rds.aliyuncs.com
    user: codemaotest
    password: dwhu8kMkgqTUwbNSCWWuBc8b
    database: account
redis:
  # 读写权限
  host: r-bp19c78721368bd4371.redis.rds.aliyuncs.com
  port: 6379
  password: liuWcl8hj3InVQONzonkIeNa